name: ClaimPlugin
main: com.pirgosth.claimPlugin.main
version: 1.0
api-version: 1.14
depend: [WorldEdit]
command-complete: true
author: Pirgosth
commands:
  test:
    description: La commande magique !
    usage: /<command>
    permission: claimPlugin.test
    permission-message: You do not have permission to do that !
  claim:
    description: Claim a wild area
    usage: /<command>
permissions:
  claimPlugin.command.test:
    description: Allow player to use test command
    default: false
  claimPlugin.command.create:
    description: Allow player to use create command
    default: false
  claimPlugin.command.info:
    description: Allow player to use info command
    default: false
  claimPlugin.command.remove:
    description: Allow player to use remove command
    default: false
  claimPlugin.command.*:
    description: Allow player to use all commands
    default: false
    children:
      claimPlugin.command.test: true
      claimPlugin.command.create: true
      claimPlugin.command.remove: true
      claimPlugin.command.info: true
  claimPlugin.others.remove:
    description: Allow player to remove others claims
    default: false
  claimPlugin.others.blocks.break:
    description: Allow player to break blocks in others claims
    default: false
  claimPlugin.others.blocks.place:
    description: Allow player to place blocks in others claims
    default: false
  claimPlugin.others.entity.hit:
    description: Allow player to hit entity in others claims
    default: false
  claimPlugin.others.interact:
    description: Allow player to interact with others claims
    default: false
  claimPlugin.others.tnt.damage.entities:
    description: Allow player's tnts to damage others claims' entities
    default: false
  claimPlugin.others.tnt.damage.blocks:
    description: Allow player's tnts to destroy others claims' blocks
    default: false
  claimPlugin.others.items.pickup:
    description: Allow player to pickup items in others claims
    default: false
  claimPlugin.others.items.drop:
    description: Allow player to drop items in others claims
    default: false
  claimPlugin.others.entities.leash:
    description: Allow player to leash others claims' entities
    default: false
  claimPlugin.others.entities.unleash:
    description: Allow player to unleash others claims' entities
    default: false
  claimPlugin.others.blocks.*:
    description: Allow player to place/break blocks in others claims
    default: false
    children:
      claimPlugin.others.blocks.break: true
      claimPlugin.others.blocks.place: true
  claimPlugin.others.tnt.damage.*:
    description: Allow player's tnts to damage others claims
    default: false
    children:
      claimPlugin.others.tnt.damage.entities: true
      claimPlugin.others.tnt.damage.blocks: true
  claimPlugin.others.items.*:
    description: Allow player to use items in others claims
    default: false
    children:
      claimPlugin.others.items.pickup: true
      claimPlugin.others.items.drop: true
  claimPlugin.others.entities.*:
    description: Allow player to leash/unleash others claims' entities
    default: false
    children:
      claimPlugin.others.entities.leash: true
      claimPlugin.others.entities.unleash: true
  claimPlugin.others.*:
    description: Granted all others permissions to player
    default: false
    children:
      claimPlugin.others.remove: true
      claimPlugin.others.blocks.*: true
      claimPlugin.others.entity.hit: true
      claimPlugin.others.interact: true
      claimPlugin.others.tnt.damage.*: true
      claimPlugin.others.items.*: true
      claimPlugin.others.entities.*: true
  claimPlugin.*:
    description: Wildcard permission
    default: op
    children:
      claimPlugin.command.*: true
      claimPlugin.others.*: true