name: XClaim
main: com.pirgosth.xclaim.main
version: 1.0
api-version: 1.15
softdepend: [Multiverse-Core]
depend: [WorldEdit, WorldGuard]
command-complete: true
author: Pirgosth
commands:
  claim:
    description: Claim a wild area
    usage: /<command>
permissions:
  xclaim.command.create:
    description: Allow player to use create command
    default: false
  xclaim.command.info:
    description: Allow player to use info command
    default: false
  xclaim.command.home:
    description: Allow player to use home command
    default: false
  xclaim.command.sethome:
    description: Allow player to use sethome command
    default: false
  xclaim.command.remove:
    description: Allow player to use remove command
    default: false
  xclaim.command.addOwner:
    description: Allow player to add an owner to a claim
    default: false
  xclaim.command.delOwner:
    description: Allow player to remove an owner from a claim
    default: false
  xclaim.command.addMember:
    description: Allow player to add a member to a claim
    default: false
  xclaim.command.delMember:
    description: Allow player to remove a member from a claim
    default: false
  xclaim.command.leave:
    description: Allow player to leave a claim
    default: false
  xclaim.command.reload:
    description: Allow player to reload all configuration files
    default: false
  xclaim.command.*:
    description: Allow player to use all commands
    default: false
    children:
      xclaim.command.create: true
      xclaim.command.home: true
      xclaim.command.sethome: true
      xclaim.command.remove: true
      xclaim.command.info: true
      xclaim.command.addOwner: true
      xclaim.command.delOwner: true
      xclaim.command.addMember: true
      xclaim.command.delMember: true
      xclaim.command.leave: true
      xclaim.command.reload: true
  xclaim.others.remove:
    description: Allow player to remove others claims
    default: false
  xclaim.others.blocks.break:
    description: Allow player to break blocks in others claims
    default: false
  xclaim.others.blocks.place:
    description: Allow player to place blocks in others claims
    default: false
  xclaim.others.entity.hit:
    description: Allow player to hit entity in others claims
    default: false
  xclaim.others.interact:
    description: Allow player to interact with others claims
    default: false
  xclaim.others.interact.armorStand:
    description: Allow player to pickup stuff on armorStand in others claims
    default: false
  xclaim.others.interact.paintings:
    description: Allow player to remove paintings in others claims
    default: false
  xclaim.others.tnt.damage.entity:
    description: Allow player's tnts to damage others claims' entities
    default: false
  xclaim.others.tnt.damage.blocks:
    description: Allow player's tnts to destroy others claims' blocks
    default: false
  xclaim.others.items.pickup:
    description: Allow player to pickup items in others claims
    default: false
  xclaim.others.items.drop:
    description: Allow player to drop items in others claims
    default: false
  xclaim.others.entity.leash:
    description: Allow player to leash others claims' entities
    default: false
  xclaim.others.entity.unleash:
    description: Allow player to unleash others claims' entities
    default: false
  xclaim.others.blocks.*:
    description: Allow player to place/break blocks in others claims
    default: false
    children:
      xclaim.others.blocks.break: true
      xclaim.others.blocks.place: true
  xclaim.others.tnt.damage.*:
    description: Allow player's tnts to damage others claims
    default: false
    children:
      xclaim.others.tnt.damage.entity: true
      xclaim.others.tnt.damage.blocks: true
  xclaim.others.items.*:
    description: Allow player to use items in others claims
    default: false
    children:
      xclaim.others.items.pickup: true
      xclaim.others.items.drop: true
  xclaim.others.entity.*:
    description: Allow player to leash/unleash others claims' entities
    default: false
    children:
      xclaim.others.entity.leash: true
      xclaim.others.entity.unleash: true
  xclaim.others.*:
    description: Granted all others permissions to player
    default: false
    children:
      xclaim.others.remove: true
      xclaim.others.blocks.*: true
      xclaim.others.entity.hit: true
      xclaim.others.interact: true
      xclaim.others.interact.armorStand: true
      xclaim.others.interact.paintings: true
      xclaim.others.tnt.damage.*: true
      xclaim.others.items.*: true
      xclaim.others.entity.*: true
  xclaim.claims.count.unlimited:
    description: Allow player to create unlimited amount of claims
    default: false
  xclaim.claims.range.unlimited:
    description: Allow player to create claims with unlimited range
    default: false
  xclaim.claims.*:
    description: Granted all claims permissions
    default: false
    children:
      xclaim.claims.count.unlimited: true
      xclaim.claims.range.unlimited: true
  xclaim.*:
    description: Wildcard permission
    default: op
    children:
      xclaim.command.*: true
      xclaim.others.*: true
      xclaim.claims.*: true
